---
sudo: false
language: ruby
bundler_args: --without system_tests
script:
  - 'puppet --version'
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=spec
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=release_checks
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=release_checks
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes" CHECK=release_checks
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6.0" STRICT_VARIABLES="yes" CHECK=release_checks
notifications:
  email: false
